# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa652ef9ddf0c15caa2ae442f3eb6a8622153f824203c7c70e797adc6a322bbc8f088954d858b0d18d1ee2a9f1e190bc86d325d3dd33cd21f000dba969d4f513

test:
  secret_key_base: dccb8f90c42347c4e83ebab192afee7817116c0bc181a680f5570816b587a3e8f8b7afb848151d4f25f6bdd32956e280dd5be248852dd307a2e5971fea838f8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
